# Generated by Django 4.2 on 2023-04-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raiting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=3000, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ContUs',
        ),
        migrations.DeleteModel(
            name='ReviewUs',
        ),
    ]
