# Generated by Django 4.2 on 2023-04-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfiles',
            name='description',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='csvfiles',
            name='fileName',
            field=models.FileField(max_length=254, upload_to=None),
        ),
        migrations.AlterField(
            model_name='csvfiles',
            name='file_link',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
