# Generated by Django 4.2 on 2023-04-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0002_csvfiles_description_alter_csvfiles_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfiles',
            name='fileName',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
