# Generated by Django 4.2 on 2023-04-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0004_loadfiles_delete_csvfiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadfiles',
            old_name='fileName',
            new_name='file',
        ),
    ]
