# Generated by Django 4.2 on 2023-04-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0005_rename_filename_loadfiles_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2500, null=True)),
                ('autority', models.CharField(choices=[('Oficial', 'Oficial'), ('Comunidad', 'Comunidad'), ('Privado', 'Privado')], max_length=80)),
                ('category', models.CharField(choices=[('Ciencia', 'Ciencia'), ('Comercio', 'Comercio'), ('Cultura', 'Cultura'), ('Educacion', 'Educacion'), ('Medicina', 'Medicina')], max_length=80)),
                ('territory', models.CharField(choices=[('Nacional', 'Nacional'), ('Departamento', 'Departamento'), ('Municipio', 'Municipio'), ('Pueblo', 'Pueblo'), ('Zona', 'Zona'), ('Barrio', 'Barrio')], max_length=20)),
                ('downloads', models.IntegerField(null=True)),
                ('views', models.IntegerField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('clasify_at', models.DateTimeField(null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LoadFiles',
        ),
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loads.basefile')),
                ('file', models.FileField(upload_to='csv/')),
                ('file_link', models.CharField(max_length=250, null=True)),
            ],
            bases=('loads.basefile',),
        ),
        migrations.CreateModel(
            name='JsonFile',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loads.basefile')),
                ('file', models.FileField(upload_to='json/')),
                ('file_link', models.CharField(max_length=250, null=True)),
            ],
            bases=('loads.basefile',),
        ),
        migrations.CreateModel(
            name='PdfFile',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loads.basefile')),
                ('file', models.FileField(upload_to='pdf/')),
                ('file_link', models.CharField(max_length=250, null=True)),
            ],
            bases=('loads.basefile',),
        ),
        migrations.CreateModel(
            name='XlsxFile',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loads.basefile')),
                ('file', models.FileField(upload_to='xlsx/')),
                ('file_link', models.CharField(max_length=250, null=True)),
            ],
            bases=('loads.basefile',),
        ),
    ]
