# Generated by Django 4.2 on 2023-04-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0007_loadfiles_remove_csvfile_basefile_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadfiles',
            name='file_ext',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
