# Generated by Django 4.2 on 2023-04-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0008_loadfiles_file_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadfiles',
            name='file_type',
        ),
        migrations.AddField(
            model_name='loadfiles',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loadfiles',
            name='license',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
