# Generated by Django 4.2 on 2023-05-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0009_remove_loadfiles_file_type_loadfiles_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadfiles',
            old_name='file',
            new_name='jsonFile',
        ),
        migrations.AddField(
            model_name='loadfiles',
            name='file_columns',
            field=models.JSONField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadfiles',
            name='file_numcols',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loadfiles',
            name='file_numrows',
            field=models.IntegerField(null=True),
        ),
    ]
