# Generated by Django 4.2 on 2023-05-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0010_rename_file_loadfiles_jsonfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadfiles',
            name='quality',
            field=models.CharField(choices=[('Abiertos', 'Abiertos'), ('Privados', 'Privados'), ('Clasificados', 'Clasificados')], default='Abiertos', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loadfiles',
            name='autority',
            field=models.CharField(choices=[('Oficial', 'Oficial'), ('Publico', 'Publico')], max_length=80),
        ),
    ]
