# Generated by Django 4.2 on 2023-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0011_loadfiles_quality_alter_loadfiles_autority'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadfiles',
            name='data_set',
            field=models.BooleanField(null=True),
        ),
    ]
