# Generated by Django 4.2 on 2023-05-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0013_loadfiles_sheet_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadfiles',
            name='territory',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Departamento', 'Departamento'), ('Municipio', 'Municipio'), ('Zona', 'Zona'), ('Barrio', 'Barrio')], max_length=20),
        ),
    ]
