# Generated by Django 4.2 on 2023-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0014_alter_loadfiles_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadfiles',
            name='zonas',
            field=models.CharField(choices=[('Curados', 'Curados'), ('Limpios', 'Limpios'), ('Raw', 'Raw'), ('Landing', 'Landing'), ('Sensitive', 'Sensitive'), ('Laboratory', 'Laboratory')], default='Landing', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loadfiles',
            name='autority',
            field=models.CharField(choices=[('Oficial', 'Oficial'), ('Publico', 'Publico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loadfiles',
            name='category',
            field=models.CharField(choices=[('Ciencia', 'Ciencia'), ('Comercio', 'Comercio'), ('Cultura', 'Cultura'), ('Educacion', 'Educacion'), ('Medicina', 'Medicina')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loadfiles',
            name='file_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loadfiles',
            name='quality',
            field=models.CharField(choices=[('Abiertos', 'Abiertos'), ('Privados', 'Privados'), ('Clasificados', 'Clasificados')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loadfiles',
            name='territory',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Departamental', 'Departamental'), ('Municipal', 'Municipal'), ('Zonal', 'Zonal'), ('Barrio', 'Barrio')], max_length=20),
        ),
    ]
