# Generated by Django 4.2 on 2023-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0015_loadfiles_zonas_alter_loadfiles_autority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadfiles',
            name='entity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loadfiles',
            name='zonas',
            field=models.CharField(choices=[('Curados', 'Curados'), ('Limpios', 'Limpios'), ('Raw', 'Raw'), ('Laboratory', 'Laboratory')], max_length=20),
        ),
    ]
