# Generated by Django 4.2 on 2023-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0016_loadfiles_entity_alter_loadfiles_zonas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadfiles',
            name='zonas',
            field=models.CharField(default='Raw', max_length=25, null=True),
        ),
    ]
