# Generated by Django 4.2 on 2023-05-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0018_dataset_sheetfile_remove_loadfiles_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetfile',
            name='sheet_columns',
            field=models.JSONField(null=True),
        ),
    ]
