# Generated by Django 4.2 on 2023-05-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0019_alter_sheetfile_sheet_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetfile',
            name='jsonFile',
        ),
    ]
