# Generated by Django 4.2 on 2023-05-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0021_alter_dataset_autority_alter_dataset_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetfile',
            name='set_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loads.dataset'),
        ),
    ]
