# Generated by Django 4.2 on 2023-05-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0023_alter_sheetfile_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetfile',
            name='set_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.dataset'),
        ),
    ]
