# Generated by Django 4.2 on 2023-05-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0024_alter_sheetfile_set_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheetfile',
            old_name='set_name',
            new_name='sheet_id',
        ),
    ]
