# Generated by Django 4.2 on 2023-05-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0025_rename_set_name_sheetfile_sheet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheetfile',
            old_name='sheet_id',
            new_name='sheet',
        ),
    ]
