# Generated by Django 4.2 on 2023-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0026_rename_sheet_id_sheetfile_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetfile',
            name='sheet_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
