# Generated by Django 4.2 on 2023-05-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0027_alter_sheetfile_sheet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetfile',
            name='sheet_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
