# Generated by Django 4.2 on 2023-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0028_alter_sheetfile_sheet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetfile',
            name='sheet',
        ),
        migrations.AlterField(
            model_name='sheetfile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
